server:
  port: 9999
eureka:
  client:
    register-with-eureka: false #是否注册自己
    fetch-registry: false #是否从eureka服务器获取注册信息
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
