server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ccms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 47.100.93.11
    port: 6379
  activemq:
    broker-url: tcp://47.100.93.11
    user: admin
    password: admin
mapper:
  identity: mysql