server:
  port: 9988
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///exam01?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  thymeleaf:
    cache: false

  redis:
    port: 6379
    host: localhost
  mvc:
    static-path-pattern: /**
#  redis:
#    cluster:
#      nodes:
#        - 192.168.83.131:7001
#        - 192.168.83.131:7002
#        - 192.168.83.131:7003
#        - 192.168.83.131:7004
#        - 192.168.83.131:7005
#        - 192.168.83.131:7006
#      max-redirects: 3
mybatis:
  mapper-locations: classpath:com/sz/wx/mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
