server:
  port: 9988
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9999/eureka/
  instance:
    prefer-ip-address: true #使用ip注册
spring:
  application:
    name: product-client #服务名称
  datasource: #数据源
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: chanpin
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
mybatis: #mybatis扫描xml路径
  mapper-locations: classpath:com/sz/product/mapper/*.xml
feign: #打开熔断器
  hystrix:
    enabled: true